name: My first workkflow

on: push

jobs:
    first_job: 
       runs-on: ubuntu-latest
       steps: 
          - name: Checkout Repo
            uses: actions/checkout@v5
            
          - name: Welcome Message
            run: echo "Im the best in github actions "

          - name: List files
            run: ls

          - name: Read file 
            run: cat README.md